"""Final feature sets, interaction rules, and model parameters."""

import pandas as pd

# 交互标记常量
positive_interactions_df = pd.DataFrame({
    "signal_name": [
        "late_severity_mid_x_short_late_low_signal",
        "late_severity_high_x_short_late_low_signal",
        "30-59late_low_x_short_late_mid_high_signal",
        "90+late_mid_high_x_short_late_low_signal",
        "30-59late_low_x_credit_late_density_mid_high_signal",
        "age_high_x_credit_late_density_high_signal",
        "util_low_x_credit_late_density_high_signal",
        "mortgage_ratio_mid_x_credit_late_density_high_signal",
        "mortgage_mid_x_credit_late_density_high_signal",
        "dep_missing_x_60-89late_mid_signal",
        "age_high_x_late_severity_high_signal",
        "age_high_x_90+late_mid_signal",
        "util_low_mid_x_late_severity_high_signal",
        "util_mid_x_90+late_mid_signal",
        "age_high_x_60-89late_mid_signal",
        "30-59late_mid_x_credit_mid_signal",
        "debt_low_x_credit_pressure_mid_signal",
        "debt_mid_x_credit_pressure_high_signal",
        "util_high_x_credit_pressure_low_signal",
        "monthly_debt_low_x_credit_pressure_high_signal",
        "late_severity_high_x_credit_pressure_low_signal",
    ],
    "binrank_colname1": [
        "late_severity_score_binrank", "late_severity_score_binrank", "30-59late_binrank",
        "90+late_binrank", "30-59late_binrank", "age_binrank", "util_binrank",
        "mortgage_ratio_binrank", "mortgage_binrank", "dep_binrank", "age_binrank",
        "age_binrank", "util_binrank", "util_binrank", "age_binrank",
        "30-59late_binrank", "debt_binrank", "debt_binrank", "util_binrank",
        "monthly_debt_binrank", "late_severity_score_binrank",
    ],
    "binrank_colname2": [
        "short_late_binrank", "short_late_binrank", "short_late_binrank",
        "short_late_binrank", "credit_late_density_binrank", "credit_late_density_binrank",
        "credit_late_density_binrank", "credit_late_density_binrank", "credit_late_density_binrank",
        "60-89late_binrank", "late_severity_score_binrank", "90+late_binrank",
        "late_severity_score_binrank", "90+late_binrank", "60-89late_binrank",
        "credit_binrank", "credit_pressure_index_binrank", "credit_pressure_index_binrank",
        "credit_pressure_index_binrank", "credit_pressure_index_binrank", "credit_pressure_index_binrank",
    ],
    "binrank1": [
        "2_2", "4_4", "1_1", "3_4", "1_1", "5_6", "1_1", "2_2", "2_2",
        "-1_-1", "6_6", "6_6", "1_2", "2_2", "6_6", "3_3", "1_1", "2_2",
        "5_5", "1_1", "4_4",
    ],
    "binrank2": [
        "1_1", "1_1", "2_4", "1_1", "4_6", "6_6", "6_6", "6_6", "6_6",
        "2_2", "4_4", "2_3", "4_4", "2_2", "2_2", "2_2", "3_4", "4_5",
        "1_2", "3_4", "1_2",
    ],
})

negative_interactions_df = pd.DataFrame({
    "signal_name": [
        "credit_low_x_util_mid_signal",
        "monthly_debt_low_x_mortgage_ratio_mid_signal",
        "credit_pressure_mid_x_debt_mid_signal",
        "monthly_debt_high_x_debt_mid_signal",
        "credit_pressure_mid_x_mortgage_mid_signal",
        "monthly_debt_low_x_mortgage_mid_signal",
        "monthly_debt_low_x_age_high_signal",
        "monthly_debt_high_x_credit_pressure_mid_high_signal",
        "monthly_debt_mid_x_credit_pressure_mid_signal",
        "age_high_x_debt_low_signal",
    ],
    "binrank_colname1": [
        "credit_binrank", "monthly_debt_binrank", "credit_pressure_index_binrank",
        "monthly_debt_binrank", "credit_pressure_index_binrank", "monthly_debt_binrank",
        "monthly_debt_binrank", "monthly_debt_binrank", "monthly_debt_binrank", "age_binrank",
    ],
    "binrank_colname2": [
        "util_binrank", "mortgage_ratio_binrank", "debt_binrank", "debt_binrank",
        "mortgage_binrank", "mortgage_binrank", "age_binrank",
        "credit_pressure_index_binrank", "credit_pressure_index_binrank", "debt_binrank",
    ],
    "binrank1": [
        "1_1", "1_1", "2_2", "4_4", "2_2", "1_1", "1_1", "4_4", "3_3", "6_6",
    ],
    "binrank2": [
        "2_2", "2_2", "2_2", "2_2", "2_2", "2_2", "6_6", "3_3", "2_2", "1_1",
    ],
})


passed_binary_colnames = [
    "blacklist_flag",
    "income_anomaly_flag",
    "has_no_credit",
    "has_serious_late",
    "has_short_late",
    "has_short_late_but_no_credit",
    "is_debt_high",
    "is_debt_overlimit",
    "is_util_high",
    "is_util_overlimit",
    "30-59late_low_x_credit_late_density_mid_high_signal",
    "30-59late_low_x_short_late_mid_high_signal",
    "30-59late_mid_x_credit_mid_signal",
    "90+late_mid_high_x_short_late_low_signal",
    "age_high_x_60-89late_mid_signal",
    "age_high_x_90+late_mid_signal",
    "age_high_x_credit_late_density_high_signal",
    "age_high_x_debt_low_signal",
    "age_high_x_late_severity_high_signal",
    "credit_low_x_util_mid_signal",
    "credit_pressure_mid_x_debt_mid_signal",
    "credit_pressure_mid_x_mortgage_mid_signal",
    "debt_low_x_credit_pressure_mid_signal",
    "debt_mid_x_credit_pressure_high_signal",
    "dep_missing_x_60-89late_mid_signal",
    "late_severity_high_x_credit_pressure_low_signal",
    "late_severity_high_x_short_late_low_signal",
    "late_severity_mid_x_short_late_low_signal",
    "monthly_debt_high_x_credit_pressure_mid_high_signal",
    "monthly_debt_high_x_debt_mid_signal",
    "monthly_debt_low_x_age_high_signal",
    "monthly_debt_low_x_credit_pressure_high_signal",
    "monthly_debt_low_x_mortgage_mid_signal",
    "monthly_debt_low_x_mortgage_ratio_mid_signal",
    "monthly_debt_mid_x_credit_pressure_mid_signal",
    "mortgage_mid_x_credit_late_density_high_signal",
    "mortgage_ratio_mid_x_credit_late_density_high_signal",
    "util_high_x_credit_pressure_low_signal",
    "util_low_mid_x_late_severity_high_signal",
    "util_low_x_credit_late_density_high_signal",
    "util_mid_x_90+late_mid_signal",
]

passed_binnames_1D = [
    "30-59late_bin",
    "60-89late_bin",
    "90+late_bin",
    "age_bin",
    "credit_bin",
    "credit_late_density_bin",
    "credit_pressure_index_bin",
    "debt_bin",
    "free_cashflow_income_bin",
    "income_bin",
    "income_per_dep_bin",
    "late_severity_score_bin",
    "mortgage_bin",
    "short_late_bin",
    "util_bin",
]

low_iv_binnames_1D = [
    "dep_bin",
    "monthly_debt_bin",
    "mortgage_ratio_bin",
]

passed_binnames_2D = [
    "credit_x_credit_pressure_index_bin",
    "dep_x_credit_bin",
    "credit_x_monthly_debt_bin",
    "debt_x_credit_bin",
    "debt_x_credit_pressure_index_bin",
    "debt_x_monthly_debt_bin",
    "debt_x_mortgage_bin",
    "debt_x_mortgage_ratio_bin",
    "income_x_monthly_debt_bin",
    "monthly_debt_x_credit_pressure_index_bin",
    "mortgage_x_credit_pressure_index_bin",
    "dep_x_mortgage_bin",
    "mortgage_x_monthly_debt_bin",
]

colnames_to_fit_raw_lr = [
    "age_centered",
    "util_centered",
    "debt_centered",
    "NumberOfDependents",
    "NumberOfOpenCreditLinesAndLoans",
    "NumberRealEstateLoansOrLines",
    "single_missing_flag",
    "both_missing_flag",
    "blacklist_flag",
    "income_anomaly_flag",
    "debt_anomaly_flag",
    "util_anomaly_flag",
    "income_per_dep_log",
    "credit_pressure_index",
    "mortgage_ratio",
    "credit_late_density",
    "short_late",
    "late_severity_score",
    "has_no_credit",
    "has_short_late_but_no_credit",
    "has_serious_late",
    "has_short_late",
    "is_debt_high",
    "is_debt_overlimit",
    "is_util_high",
    "is_util_overlimit",
]
c_raw_lr = 1

colnames_to_fit_woe_lr = [
    "age_bin_woe",
    "util_bin_woe",
    "debt_bin_woe",
    "credit_bin_woe",
    "mortgage_bin_woe",
    "income_per_dep_bin_woe",
    "credit_pressure_index_bin_woe",
    "late_severity_score_bin_woe",
    "has_no_credit_woe",
    "has_short_late_but_no_credit_woe",
    "has_serious_late_woe",
    "blacklist_flag_woe",
    "is_debt_high_woe",
    "is_debt_overlimit_woe",
    "is_util_high_woe",
    "is_util_overlimit_woe",
    "dep_x_credit_bin_woe",
    "credit_x_monthly_debt_bin_woe",
    "debt_x_credit_bin_woe",
    "debt_x_credit_pressure_index_bin_woe",
    "debt_x_monthly_debt_bin_woe",
    "debt_x_mortgage_bin_woe",
    "debt_x_mortgage_ratio_bin_woe",
    "income_x_monthly_debt_bin_woe",
    "dep_x_mortgage_bin_woe",
    "mortgage_x_monthly_debt_bin_woe",
]
c_woe_lr = 0.025

colnames_to_fit_xgb = [
    "Age",
    "RevolvingUtilizationOfUnsecuredLines",
    "DebtRatio",
    "MonthlyIncome",
    "NumberOfDependents",
    "NumberOfOpenCreditLinesAndLoans",
    "NumberRealEstateLoansOrLines",
    "NumberOfTime30-59DaysPastDueNotWorse",
    "NumberOfTime60-89DaysPastDueNotWorse",
    "NumberOfTimes90DaysLate",
    "free_cashflow_income",
    "credit_pressure_index",
    "credit_late_density",
    "mortgage_ratio",
    "late_severity_score",
]

best_para_xgb_dict = dict(
    max_depth=3,
    min_child_weight=7,
    learning_rate=0.03,
    n_estimators=800,
    subsample=0.7,
    colsample_bytree=0.6,
    reg_alpha=1,
    reg_lambda=2,
)

